nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/plugin-prepare-lifecycle.cjs
    spec: "https://github.com/un-es/yarn-plugin-prepare-lifecycle/releases/download/v0.0.1/index.js"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
