name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch: null

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint
